[package]
name = "rust_particle_system"
version = "1.0.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
image = "0.24.6"
clap = {version = "3.1.6", features = ["derive", "cargo"]}

[profile.release]
debug = true # for profiling
